spring:
  application:
    name: edging-service
zuul:
  routes:
    order-service:
      path: /order-service/**
      url: http://localhost:9000
    menu-service:
      path: /menu-service/**
      url: http://localhost:9001
    payment-service:
      path: /payment-service/**
      url: http://localhost:9002
    cart-service:
      path: /cart-service/**
      url: http://localhost:9003